services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@todo
      POSTGRES_DB: todo
    volumes:
      - todo-data:/var/lib/postgresql/data
      - ./dev/sql/init:/docker-entrypoint-initdb.d
volumes:
  todo-data:

