-- TODOテーブルの作成
DROP TABLE IF EXISTS todo
;

CREATE TABLE todo (
    todo_id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pkey_t_todo PRIMARY KEY,
    user_id VARCHAR(20) NOT NULL,
    todo_date DATE,
    todo_title VARCHAR(30) NOT NULL,
    todo_content VARCHAR(100),
    is_complete BOOLEAN NOT NULL DEFAULT (FALSE),
    version INTEGER NOT NULL DEFAULT (1),
    created_by VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(20),
    updated_at TIMESTAMP
)
;